'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import store from '@/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CryptoVerse',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>

    <html lang="en">
      <body className={inter.className}>

        <Navbar/>
        {children}</body>
    </html>
    </Provider>
  )
}
